import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import { cn } from "~/lib/utils";
import SessionProvider from "~/components/session-provider";
import ThemeProvider from "~/components/theme-provider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Sonic Jam",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  console.log(session);

  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-white font-sans text-neutral-900 antialiased dark:bg-primary-950 dark:text-neutral-100",
          inter.variable,
        )}
      >
        <SessionProvider session={session}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
