import "~/styles/globals.css";

import { Noto_Sans_JP } from "next/font/google";
import { cn } from "~/lib/utils";
import ThemeProvider from "~/components/theme-provider";
import { NextIntlClientProvider, useMessages } from "next-intl";

const font = Noto_Sans_JP({
  subsets: ["latin", "vietnamese"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Sonic Jam",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = useMessages();
  return (
    <html lang={locale}>
      <body
        className={cn(
          "min-h-screen bg-white font-sans text-neutral-900 antialiased dark:bg-primary-950 dark:text-neutral-100",
          font.variable,
        )}
      >
        <NextIntlClientProvider messages={messages}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
